pluginGroup=com.alicejump.oklanghints
pluginName=ok-script Lang Hints
pluginVersion=0.1.0
platformVersion=2025.1.1.1
platformLocalPath=D:/IDE/PyCharm
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.java.installations.paths=D:/IDE/PyCharm/jbr
